/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.controleacesso.view;

import javax.swing.JButton;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author gomes
 */
public class DashboardView extends JInternalFrame {

    /**
     * Creates new form DashboardView
     */
    public DashboardView() {
        initComponents();
        setClosable(true);
        setResizable(true);
        setIconifiable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        btnNovoUsuario = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTabelaUsuarios = new javax.swing.JTable();
        btnAutorizarAcesso = new javax.swing.JButton();
        btnRejeitarAcesso = new javax.swing.JButton();
        lblTituloTabela = new javax.swing.JLabel();
        btnPromoverUsuario = new javax.swing.JButton();
        btnRebaixarUsuario = new javax.swing.JButton();
        btnListagemUsuarios = new javax.swing.JButton();
        btnAutorizacoesPendentes = new javax.swing.JButton();
        btnRemoverUsuario = new javax.swing.JButton();
        btnAlterarSenha = new javax.swing.JButton();
        btnConfiguracaoLog = new javax.swing.JButton();
        lblNavegacao = new javax.swing.JLabel();
        lblAcoesGlobais = new javax.swing.JLabel();
        lblPessoal = new javax.swing.JLabel();
        lblAcoesSelecao = new javax.swing.JLabel();
        btnSair = new javax.swing.JButton();
        btnRestaurarSistema = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblUsuario = new javax.swing.JLabel();
        lblPerfil = new javax.swing.JLabel();
        txtNomeUsuario = new javax.swing.JTextField();
        txtDescPerfil = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(815, 560));

        lblTitulo.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Controle de Acesso");

        btnNovoUsuario.setText("Cadastrar Usuário");

        tblTabelaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane1.setViewportView(tblTabelaUsuarios);

        btnAutorizarAcesso.setText("Autorizar");
        btnAutorizarAcesso.setToolTipText("Autoriza o usuario selecionado a acessar o sistema.");

        btnRejeitarAcesso.setText("Rejeitar");
        btnRejeitarAcesso.setToolTipText("Rejeita o acesso do usuario selecionado ao sistema.");

        lblTituloTabela.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblTituloTabela.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloTabela.setText("Autorizações Pendentes");

        btnPromoverUsuario.setText("Promover");
        btnPromoverUsuario.setToolTipText("Promove o usuario selecionado para administrador.");

        btnRebaixarUsuario.setText("Rebaixar");
        btnRebaixarUsuario.setToolTipText("Rebaixa o usuario de administrador para usuario padrao.");

        btnListagemUsuarios.setText("Listar Usuários");

        btnAutorizacoesPendentes.setText("Autorizações Pendentes");
        btnAutorizacoesPendentes.setToolTipText("Lista os usuarios que estao com autorizacao pendente.");

        btnRemoverUsuario.setText("Remover");
        btnRemoverUsuario.setToolTipText("Remove o usuario selecionado do sistema.");

        btnAlterarSenha.setText("Alterar Minha Senha");

        btnConfiguracaoLog.setText("Configuração de Logs");

        lblNavegacao.setFont(new java.awt.Font("JetBrains Mono NL", 0, 12)); // NOI18N
        lblNavegacao.setText(" --------- Navegacao ---------");

        lblAcoesGlobais.setFont(new java.awt.Font("JetBrains Mono NL", 0, 12)); // NOI18N
        lblAcoesGlobais.setText(" ------ Acoes Globais --------");

        lblPessoal.setFont(new java.awt.Font("JetBrains Mono NL", 0, 12)); // NOI18N
        lblPessoal.setText(" ----- Pessoal / Sistema -----");

        lblAcoesSelecao.setFont(new java.awt.Font("JetBrains Mono NL", 0, 12)); // NOI18N
        lblAcoesSelecao.setText(" ------ Acoes de Selecao -----");

        btnSair.setText("Sair");

        btnRestaurarSistema.setText("RESTAURAR");

        lblUsuario.setText("Usuário:");

        lblPerfil.setText("Perfil:");

        txtNomeUsuario.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N

        txtDescPerfil.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDescPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(txtNomeUsuario))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario)
                    .addComponent(txtNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPerfil)
                    .addComponent(txtDescPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTituloTabela, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNavegacao, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAcoesGlobais, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNovoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPessoal, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAutorizarAcesso, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRejeitarAcesso, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPromoverUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRebaixarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAlterarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRemoverUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAcoesSelecao, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnConfiguracaoLog, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAutorizacoesPendentes, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnListagemUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addComponent(btnRestaurarSistema)
                                .addGap(18, 18, 18)
                                .addComponent(btnSair))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTitulo)
                        .addComponent(btnSair)
                        .addComponent(btnRestaurarSistema))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblTituloTabela)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNavegacao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnListagemUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAutorizacoesPendentes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAcoesGlobais)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNovoUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAcoesSelecao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAutorizarAcesso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRejeitarAcesso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPromoverUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRebaixarUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRemoverUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPessoal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAlterarSenha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnConfiguracaoLog)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setBounds(0, 0, 804, 560);
    }// </editor-fold>//GEN-END:initComponents

    private void btnListagemUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListagemUsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnListagemUsuariosActionPerformed

    private void btnRebaixarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRebaixarUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRebaixarUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarSenha;
    private javax.swing.JButton btnAutorizacoesPendentes;
    private javax.swing.JButton btnAutorizarAcesso;
    private javax.swing.JButton btnConfiguracaoLog;
    private javax.swing.JButton btnListagemUsuarios;
    private javax.swing.JButton btnNovoUsuario;
    private javax.swing.JButton btnPromoverUsuario;
    private javax.swing.JButton btnRebaixarUsuario;
    private javax.swing.JButton btnRejeitarAcesso;
    private javax.swing.JButton btnRemoverUsuario;
    private javax.swing.JButton btnRestaurarSistema;
    private javax.swing.JButton btnSair;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAcoesGlobais;
    private javax.swing.JLabel lblAcoesSelecao;
    private javax.swing.JLabel lblNavegacao;
    private javax.swing.JLabel lblPerfil;
    private javax.swing.JLabel lblPessoal;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTituloTabela;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JTable tblTabelaUsuarios;
    private javax.swing.JTextField txtDescPerfil;
    private javax.swing.JTextField txtNomeUsuario;
    // End of variables declaration//GEN-END:variables
    
    public JLabel getLblTituloTabela() {
        return lblTituloTabela;
    }
    
    public JButton getBtnNovoUsuario() {
        return btnNovoUsuario;
    }
    
    public JButton getBtnAutorizarAcesso() {
        return btnAutorizarAcesso;
    }
    
    public JButton getBtnRejeitarAcesso() {
        return btnRejeitarAcesso;
    }
    
    public JButton getBtnPromoverUsuario() {
        return btnPromoverUsuario;
    }
    
    public JButton getBtnRebaixarUsuario() {
        return btnRebaixarUsuario;
    }
    
    public JButton getBtnListagemUsuarios() {
        return btnListagemUsuarios;
    }
    
    public JButton getBtnAutorizacoesPendentes() {
        return btnAutorizacoesPendentes;
    }
    
    public JTable getTabelaUsuarios() {
        return tblTabelaUsuarios;
    }
    
    public JButton getBtnRemoverUsuario() {
        return btnRemoverUsuario;
    }
    
    public JButton getBtnAlterarSenha() {
        return btnAlterarSenha;
    }
    
    public JButton getBtnConfiguracaoLog() {
        return btnConfiguracaoLog;
    }
    
    public JLabel getLblAcoesGlobais() {
        return lblAcoesGlobais;
    }
    
    public JLabel getLblAcoesSelecao() {
        return lblAcoesSelecao;
    }
    
    public JButton getBtnSair() {
        return btnSair;
    }
    
    public JButton getBtnRestaurarSistema() {
        return btnRestaurarSistema;
    }
    
    public JTextField getTxtNomeUsuario() {
        return txtNomeUsuario;
    }
    
    public JTextField getTxtDescPerfil() {
        return txtDescPerfil;
    }
}
