/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.controleacesso.view;

import javax.swing.JButton;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.JTable;

/**
 *
 * @author gomes
 */
public class DashboardView extends JInternalFrame {

    /**
     * Creates new form DashboardView
     */
    public DashboardView() {
        initComponents();
        setClosable(true);
        setResizable(true);
        setIconifiable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        btnNovoUsuario = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTabelaUsuarios = new javax.swing.JTable();
        btnAutorizarAcesso = new javax.swing.JButton();
        btnRejeitarAcesso = new javax.swing.JButton();
        lblTituloTabela = new javax.swing.JLabel();
        btnPromoverUsuario = new javax.swing.JButton();
        btnRebaixarUsuario = new javax.swing.JButton();
        btnListagemUsuarios = new javax.swing.JButton();
        btnAutorizacoesPendentes = new javax.swing.JButton();
        btnRemoverUsuario = new javax.swing.JButton();
        btnAlterarSenha = new javax.swing.JButton();
        btnConfiguracaoLog = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblAcoesGlobais = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblAcoesSelecao = new javax.swing.JLabel();
        btnSair = new javax.swing.JButton();
        btnRestaurarSistema = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(815, 560));

        lblTitulo.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Controle de Acesso");

        btnNovoUsuario.setText("Cadastrar Usuário");

        tblTabelaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane1.setViewportView(tblTabelaUsuarios);

        btnAutorizarAcesso.setText("Autorizar");
        btnAutorizarAcesso.setToolTipText("Autoriza o usuario selecionado a acessar o sistema.");

        btnRejeitarAcesso.setText("Rejeitar");
        btnRejeitarAcesso.setToolTipText("Rejeita o acesso do usuario selecionado ao sistema.");

        lblTituloTabela.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblTituloTabela.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloTabela.setText("Autorizações Pendentes");

        btnPromoverUsuario.setText("Promover");
        btnPromoverUsuario.setToolTipText("Promove o usuario selecionado para administrador.");

        btnRebaixarUsuario.setText("Rebaixar");
        btnRebaixarUsuario.setToolTipText("Rebaixa o usuario de administrador para usuario padrao.");

        btnListagemUsuarios.setText("Listar Usuários");

        btnAutorizacoesPendentes.setText("Autorizações Pendentes");
        btnAutorizacoesPendentes.setToolTipText("Lista os usuarios que estao com autorizacao pendente.");

        btnRemoverUsuario.setText("Remover");
        btnRemoverUsuario.setToolTipText("Remove o usuario selecionado do sistema.");

        btnAlterarSenha.setText("Alterar Minha Senha");

        btnConfiguracaoLog.setText("Configuração de Logs");

        jLabel1.setFont(new java.awt.Font("JetBrains Mono NL", 0, 12)); // NOI18N
        jLabel1.setText(" --------- Navegacao ---------");

        lblAcoesGlobais.setFont(new java.awt.Font("JetBrains Mono NL", 0, 12)); // NOI18N
        lblAcoesGlobais.setText(" ------ Acoes Globais --------");

        jLabel3.setFont(new java.awt.Font("JetBrains Mono NL", 0, 12)); // NOI18N
        jLabel3.setText(" ----- Pessoal / Sistema -----");

        lblAcoesSelecao.setFont(new java.awt.Font("JetBrains Mono NL", 0, 12)); // NOI18N
        lblAcoesSelecao.setText(" ------ Acoes de Selecao -----");

        btnSair.setText("Sair");

        btnRestaurarSistema.setText("RESTAURAR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRestaurarSistema)
                        .addGap(18, 18, 18)
                        .addComponent(btnSair))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(224, 224, 224)
                                .addComponent(lblTituloTabela, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblAcoesGlobais, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnNovoUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAutorizarAcesso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnRejeitarAcesso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnPromoverUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnRebaixarUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAlterarSenha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnRemoverUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblAcoesSelecao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnConfiguracaoLog, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnAutorizacoesPendentes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnListagemUsuarios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitulo)
                    .addComponent(btnSair)
                    .addComponent(btnRestaurarSistema))
                .addGap(18, 18, 18)
                .addComponent(lblTituloTabela)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnListagemUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAutorizacoesPendentes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAcoesGlobais)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNovoUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAcoesSelecao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAutorizarAcesso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRejeitarAcesso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPromoverUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRebaixarUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRemoverUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAlterarSenha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnConfiguracaoLog)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        setBounds(0, 0, 804, 560);
    }// </editor-fold>//GEN-END:initComponents

    private void btnListagemUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListagemUsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnListagemUsuariosActionPerformed

    private void btnRebaixarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRebaixarUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRebaixarUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarSenha;
    private javax.swing.JButton btnAutorizacoesPendentes;
    private javax.swing.JButton btnAutorizarAcesso;
    private javax.swing.JButton btnConfiguracaoLog;
    private javax.swing.JButton btnListagemUsuarios;
    private javax.swing.JButton btnNovoUsuario;
    private javax.swing.JButton btnPromoverUsuario;
    private javax.swing.JButton btnRebaixarUsuario;
    private javax.swing.JButton btnRejeitarAcesso;
    private javax.swing.JButton btnRemoverUsuario;
    private javax.swing.JButton btnRestaurarSistema;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAcoesGlobais;
    private javax.swing.JLabel lblAcoesSelecao;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTituloTabela;
    private javax.swing.JTable tblTabelaUsuarios;
    // End of variables declaration//GEN-END:variables
    
    public JLabel getLblTituloTabela() {
        return lblTituloTabela;
    }
    
    public JButton getBtnNovoUsuario() {
        return btnNovoUsuario;
    }
    
    public JButton getBtnAutorizarAcesso() {
        return btnAutorizarAcesso;
    }
    
    public JButton getBtnRejeitarAcesso() {
        return btnRejeitarAcesso;
    }
    
    public JButton getBtnPromoverUsuario() {
        return btnPromoverUsuario;
    }
    
    public JButton getBtnRebaixarUsuario() {
        return btnRebaixarUsuario;
    }
    
    public JButton getBtnListagemUsuarios() {
        return btnListagemUsuarios;
    }
    
    public JButton getBtnAutorizacoesPendentes() {
        return btnAutorizacoesPendentes;
    }
    
    public JTable getTabelaUsuarios() {
        return tblTabelaUsuarios;
    }
    
    public JButton getBtnRemoverUsuario() {
        return btnRemoverUsuario;
    }
    
    public JButton getBtnAlterarSenha() {
        return btnAlterarSenha;
    }
    
    public JButton getBtnConfiguracaoLog() {
        return btnConfiguracaoLog;
    }
    
    public JLabel getLblAcoesGlobais() {
        return lblAcoesGlobais;
    }
    
    public JLabel getLblAcoesSelecao() {
        return lblAcoesSelecao;
    }
    
    public JButton getBtnSair() {
        return btnSair;
    }
    
    public JButton getBtnRestaurarSistema() {
        return btnRestaurarSistema;
    }
    
}
